DB_TABLENAME_USERS = "users"
DB_TABLENAME_USER_PROFILES = "user_profile"
DB_TABLENAME_USER_POLICIES = "user_policies"
DB_TABLENAME_USER_ROLES = "user_roles"
DB_TABLENAME_ROLES = "roles"
DB_TABLENAME_ROLE_PERMISSIONS = "role_permissions"
DB_TABLENAME_LOGIN_DATES = "login_dates"
DB_TABLENAME_PERMISSIONS = "permissions"
DB_TABLENAME_MANUFACTURERS = "manufacturers"
DB_TABLENAME_SPECIALIZED_FIELDS = "specialized_fields"

RSHIP_TYPES = ["1:1", "1:n", "n:m"]
